name: cpplint
on: [push, pull_request]
jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - run: pip install cpplint
    # - run: cpplint --filter=  # print out all cpplint rules
    - run: cpplint --recursive . || true  # all issues to be fixed
